### ISSUE TITLE
openwrt php5 date() error.

### ISSUE THREAD

**Issue by tlze** [maysrp/webdir#4]
Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.

**Comment by maysrp** [comment]
1.set “php.ini”
`date.timezone = "Asia/Shanghai"`
restart your php service.
OR
2.
At the beginning of the script, add the following statement
`date_default_timezone_set('PRC'); 
`
OR
3.
At the beginning of the script, add the following statement
` ini_set('date.timezone','Asia/Shanghai');`

**Comment by tlze** [comment]
I have tryed to set "php.ini".
but still have error.

Warning: date(): Invalid date.timezone value 'Asia/Shanghai', we selected the timezone 'UTC' for now. in /www/index.php on line 151
Fatal error: date(): Timezone database is corrupt - this should *never* happen! in /www/index.php on line 151

I don't know script, I passed 2 and 3。
Thanks you.

**Comment by maysrp** [comment]
https://forum.openwrt.org/viewtopic.php?id=33864

**Comment by tlze** [comment]
Thank you very much, now it works.
